---
- name: Conditional upgrade and config patch
  hosts: all
  become: true
  vars:
    file_src: "/Users/manju/Downloads/upgrade-dbs/1.70.0/raniotNet"
    file_dest: "/home/skybase/upgrade/"
    upgrade_script: /home/skybase/upgrade/im-installer-standalone-3.0.0.sh
    config_file: /opt/skylo/im/raniot-im-launcher.json
    systemd_service: raniot-im-launcher.service
    install_marker: /opt/skylo/im/.install_done

  tasks:
    - name: Copy file to remote servers
      copy:
        src: "{{ file_src }}"
        dest: "{{ file_dest }}"
      delegate_to: "{{ inventory_hostname }}"

    - name: Ensure upgrade script is executable
      file:
        path: "{{ upgrade_script }}"
        mode: '0755'

    - name: Check if installation is already done
      stat:
        path: "{{ install_marker }}"
      register: install_status

    - name: Execute the upgrade script with -y flag if not already installed
      shell: "bash {{ upgrade_script }} -y && touch {{ install_marker }}"
      when: not install_status.stat.exists
      args:
        executable: /bin/bash

    - name: Pause for 10 seconds if upgrade ran
      pause:
        seconds: 5
      when: not install_status.stat.exists

    - name: Check if config file contains '04'
      shell: "grep -q '04' {{ config_file }}"
      register: sed_check
      ignore_errors: true

    - name: Replace '04' with '11' in JSON config file if needed
      shell: "sed -i 's/04/11/g' {{ config_file }}"
      when: sed_check.rc == 0

    - name: Restart the raniot-im-launcher service
      systemd:
        name: "{{ systemd_service }}"
        state: restarted
