
obs:
  hosts:
    LAB-OBS02-N1:
      ansible_host: 192.168.100.115
      ansible_user: skybase
      ansible_connection: ssh
      ansible_ssh_pass: skybase123
      become_user: root
      ansible_become_password: skybase123
      kango_name: LAB-OBS01-N1

    LAB-OBS02-N2:
      ansible_host: 192.168.100.140
      ansible_user: skybase
      ansible_connection: ssh
      ansible_ssh_pass: skybase123
      become_user: root 
      ansible_become_password: skybase123    
      kango_name: LAB-OBS01-N2

    LAB-OBS03-N1:
      ansible_host: 192.168.100.117
      ansible_user: skybase
      ansible_connection: ssh
      ansible_ssh_pass: skybase123
      become_user: root
      ansible_become_password: skybase123
      kango_name: LAB-OBS01-N1

    LAB-OBS03-N2:
      ansible_host: 192.168.100.155
      ansible_user: skybase
      ansible_connection: ssh
      ansible_ssh_pass: skybase123
      become_user: root 
      ansible_become_password: skybase123    
      kango_name: LAB-OBS01-N2
    

all:
  vars:

    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'    
    mnc: 999
    mcc: 901
    