
obs:
  hosts:
    LAS-12-OBS01-N1:
      ansible_host: 192.168.100.138
      ansible_user: skybase
      ansible_connection: ssh
      ansible_ssh_pass: skybase123     
      become_user: root 
      ansible_become_password: skybase123    
      kango_name: LAS-12-OBS01-N1

    LAS-12-OBS01-N2:
      ansible_host: 192.168.100.153
      ansible_user: skybase
      ansible_connection: ssh
      ansible_ssh_pass: skybase123     
      become_user: root 
      ansible_become_password: skybase123              
      kango_name: LAS-12-OBS01-N2
    

all:
  vars:

    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'    
    mnc: 901
    mcc: 999
    