obs:
  hosts:

    DLS-01-QBS01:
        ansible_host: 172.26.2.23
        ansible_user: skybase
        ansible_connection: ssh
        ansible_ssh_pass: skybase123
        become_user: root
        ansible_become_password: skybase123
        kango_name: LAB-OBS01-N1
    

all:
  vars:

    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'    
    mcc: 901
    mnc: 999
    EMS: true #disable EMS
    eNB_config_template: raniotNet_echostar_eu.conf
    EMSRMQAddress: ems-rmq.dev.skylo.tech